### ISSUE TITLE
mermaid diagram

### ISSUE THREAD

**Issue by KoenigMathieu** [andygolubev/integration-cookbook#1]
Hello,

nice project :)

Do you ever try to post mermaid diagram ? 
but maybe it depends on mermaid plugin..

Thansk

**Comment by andygolubev** [comment]
Hi!

I've honestly never used mermaid diagrams :)

With a quick search I found a project like this: https://pypi.org/project/markdown-mermaid-to-images/
That is, you can first process the mermaid files and then load the finished markdown into Confluence as text and images.

**Comment by KoenigMathieu** [comment]
well, thank you
it's a good approach
